image: docker:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  ARTIFACTORY_URL: "artifactory.tools.in.pan-net.eu"
  ARTIFACTORY_REGISTRY: "net_mon-images-docker-local"
  ARTIFACTORY_LOGIN: "f540422"

cache:
  paths:
    - .cache/pip

before_script:
  - apk add --no-cache curl py-pip python3-dev libffi-dev openssl-dev gcc libc-dev make
  - pip3 install docker-compose

stages:
  - test
  - push_docker

test:
  stage: test
  script:
    - docker-compose -f docker-compose-test.yml down -v
    - docker-compose -f docker-compose-test.yml build
    - docker-compose -f docker-compose-test.yml up --exit-code-from tests --abort-on-container-exit
  after_script:
    - docker-compose -f docker-compose-test.yml down -v
  only:
    - tags

build_push_docker_image_tagged:
  stage: push_docker
  tags:
    - docker-build
  environment:
      name: $CI_COMMIT_REF_NAME
  script:
    - docker-compose -f docker-compose.yml build
    - export
    - docker login -u ${ARTIFACTORY_LOGIN} -p ${ARTIFACTORY_TOKEN} https://${ARTIFACTORY_URL}
    - docker tag kafka-go-streamer:latest  ${ARTIFACTORY_URL}/${ARTIFACTORY_REGISTRY}/docker-images/${CI_PROJECT_NAME}:$CI_COMMIT_TAG
    - docker push ${ARTIFACTORY_URL}/${ARTIFACTORY_REGISTRY}/docker-images/${CI_PROJECT_NAME}:$CI_COMMIT_TAG
  only:
    - tags
