FROM golang:1.15-alpine

WORKDIR /go/src/gitlab.tools.in.pan-net.eu/security/kafka-go-streamer
ENV GOPATH=/go
ENV GO111MODULE=on

RUN set -ex \
    && apk add --no-cache --virtual .build-deps \
            git \
            gcc \
            g++ \
            make \
            libc-dev \
            musl-dev \
            linux-headers

COPY . /go/src/gitlab.tools.in.pan-net.eu/security/kafka-go-streamer

COPY ./docker/kafka-go-streamer/wait-for-kafka.sh /opt
RUN chmod u+x /opt/wait-for-kafka.sh

CMD ["/opt/wait-for-kafka.sh", "/usr/local/go/bin/go", "test", "-v", "./..."]
